import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

const inter = Inter({
  subsets: ['latin'],
  // weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Proudhon',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<React.PropsWithChildren> = async ({ children }) => {
  const theme = cookies().get('theme')?.value
  return (
    <html lang="en" {...(theme === 'dark' && { className: 'dark' })}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default RootLayout
